# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=120)),
                ('lname', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=500)),
                ('officeEmail', models.CharField(max_length=100)),
                ('mob', models.IntegerField()),
                ('where', models.CharField(max_length=500)),
            ],
        ),
    ]
