# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyuser',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
